language: node_js
node_js:
  - "6"
  - "7"
env:
  - NODE_ENV="development"
  - CXX=g++-4.8
install:
  - npm install
script:
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
